USE [master]
GO

CREATE DATABASE [Brazilian_Ecommerce_DW_DW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Brazilian_Ecommerce_DW_dw_data', FILENAME = N'C:\MSSQL\DATA\brazil_ecommerce_dw.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 262144KB ), 
 FILEGROUP [INDEXES] 
( NAME = N'Brazilian_Ecommerce_DW_dw_indexes', FILENAME = N'C:\MSSQL\DATA\brazil_ecommerce_dw.ndf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 262144KB )
 LOG ON 
( NAME = N'Brazilian_Ecommerce_DW_dw_log', FILENAME = N'J:\MSSQL\LOG\brazil_ecommerce_dw.ldf' , SIZE = 532480KB , MAXSIZE = 2048GB , FILEGROWTH = 262144KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] MODIFY FILEGROUP [PRIMARY] AUTOGROW_ALL_FILES
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Brazilian_Ecommerce_DW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET ARITHABORT OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET CURSOR_CLOSE_ON_COMMIT ON 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET  MULTI_USER 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Brazilian_Ecommerce_DW] SET  READ_WRITE 
GO


