SELECT * FROM [Brazilian_Ecommerce_DW].[dbo].[vwCustomerMeasures]
ORDER BY QTY_CUSTOMERS ASC
	,QTY_CUSTOMERS_ROWNUMBER ASC
	,RANK_QTY_CUSTOMERS ASC
	,RANK_CUSTOMER_STATE ASC
	,DENSE_RANK_QTY_CUSTOMER_STATE ASC